### ISSUE TITLE
/api/user and /api/token are the same

### ISSUE THREAD

**Issue by bullfest** [datasektionen/pls#7]
`/api/user` and `/api/token` behave exactly the same way, we should rewrite it so that `/user` only allows uid:s and `/token` only allows tokens.

**Comment by addreas** [comment]
[This statement](https://github.com/datasektionen/pls/blob/f49eb172b53e96ecf36a9000cc7853019d51233b/lib/pls/queries/user.ex#L20) should be moved into `queries/token.ex`, and `router/token.ex` should be changed to point towards that instead.

**Comment by addreas** [comment]
Probably fixed in 05d54cc.
